# -*- coding: utf-8 -*-
"""jpmedical.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T0rFmiMrPpM7Z86R-MLgRjVz-Bq4Vsrh
"""

from calendar import c
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import csv
from pathlib import Path
import os
#CSVファイルをUTF-8形式で読み込む
pd.options.display.max_rows = None
pd.options.display.max_columns = None
with open("../0101.csv", "r", encoding="shift_jis", errors="", newline="" ) as f:
    lst = csv.reader(f, delimiter=",")
    df = pd.DataFrame(lst)
df

df2 = df.head(79)
df3 = df2.tail(62)
df3

df4 = df3.dropna(how='all',axis=1)
df4=df4.iloc[:, list([3])]
df4=df4.drop([22,28,34,40,46,52,58,64,70,76], axis=0)
df4

df5 = df4[3].str.replace('.', '')
df6 = df5.values
df7=df6.astype(int)
df8 = df7*79
df9 = pd.DataFrame(df8)
df9

df9.plot()         
plt.xticks([]) 
plt.savefig('result.png')                  
plt.show()
